env:
  es2021: true
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  import/extensions: 0
  no-await-in-loop: 0
  no-console: 0
  arrow-parens: 0
